#include QMK_KEYBOARD_H
#include <keymap_jp.h>
// #include sendstring_jis.h

// enum custom_keycodes { myAster = SAFE_RANGE, QMKBEST, myPlus };

// bool process_record_user(uint16_t keycode, keyrecord_t *record) {
//     switch (keycode) {
//         case QMKBEST:
//             if (record->event.pressed) SEND_STRING("test");         break;
//     }
//     return true;
// };


const key_override_t oneToPer = ko_make_basic(MOD_MASK_SHIFT, KC_1, JP_PERC);//1   *   %



// This globally defines all key overrides to be used
const key_override_t **key_overrides = (const key_override_t *[]){
    &oneToPer,
    NULL  // Null terminate the array of overrides!
};


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_4key(\
        KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_EQL,                KC_JYEN, KC_6,KC_7, KC_8, KC_9, KC_0, KC_MINS,\
        KC_ESC, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_RBRC,               KC_RO, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, \
        KC_TAB, KC_A, KC_S, KC_D, KC_F, KC_G, KC_NUHS,               KC_DEL, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, \
        KC_GRV, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_GRV,                KC_BSPC, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_GRV,\
        KC_LGUI, KC_LALT, MO(1), KC_LCTL, MO(2), KC_LSFT, KC_SPC,    KC_ENT, KC_RSFT, MO(3), KC_RCTL, MO(1), KC_RALT, KC_RGUI\
        ),
                                                              [1] = LAYOUT_4key(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_KANA, KC_KANA, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MUTE, KC_F9, KC_F10, KC_F11, KC_F12, KC_LALT, KC_HENK, KC_HENK, KC_RALT, KC_F9, KC_F10, KC_F11, KC_F12, KC_MUTE, KC_VOLU, KC_F5, KC_F6, KC_F7, KC_F8, KC_LSFT, KC_MHEN, KC_MHEN, KC_RSFT, KC_F5, KC_F6, KC_F7, KC_F8, KC_VOLU, KC_VOLD, KC_F1, KC_F2, KC_F3, KC_F4, KC_LCTL, KC_NO, KC_NO, KC_RCTL, KC_F1, KC_F2, KC_F3, KC_F4, KC_VOLD, KC_LGUI, KC_LALT, KC_TRNS, KC_LCTL, KC_LCTL, KC_LSFT, KC_LALT, KC_RALT, KC_RSFT, KC_RCTL, KC_RCTL, KC_TRNS, KC_RALT, KC_RGUI),
                                                              [2] = LAYOUT_4key(KC_INS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_DEL, KC_NLCK, KC_P7, KC_P8, KC_P9, KC_PAST, KC_PMNS, KC_INS, KC_NO, KC_BSPC, KC_SPC, KC_ENT, KC_DEL, KC_CAPS, KC_BSPC, KC_P0, KC_P4, KC_P5, KC_P6, KC_PSLS, KC_PPLS, KC_DEL, KC_NO, KC_LEFT, KC_UP, KC_DOWN, KC_RGHT, KC_APP, KC_ENT, KC_PDOT, KC_P1, KC_P2, KC_P3, KC_RO, KC_NO, KC_BSPC, KC_NO, KC_HOME, KC_PGUP, KC_PGDN, KC_END, KC_SLCK, KC_LGUI, KC_LALT, KC_NO, KC_LCTL, KC_TRNS, KC_NO, KC_NO, KC_ENT, KC_RSFT, KC_GRV, KC_RCTL, KC_NO, KC_RALT, KC_RGUI),
                                                              [3] = LAYOUT_4key(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_DEL, KC_NO, KC_BTN5, KC_BTN4, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_DEL, KC_BSPC, KC_MS_L, KC_MS_U, KC_MS_D, KC_MS_R, KC_NO, KC_NO, KC_NO, KC_NO, KC_ACL2, KC_ACL1, KC_RSFT, KC_RCTL, KC_BSPC, KC_ENT, KC_WH_L, KC_WH_U, KC_WH_D, KC_WH_R, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_ACL0, KC_RALT, KC_NO, KC_ENT, KC_LGUI, KC_LALT, KC_NO, KC_LCTL, KC_BTN2, KC_BTN1, KC_BTN3, KC_NO, KC_NO, KC_TRNS, KC_RCTL, KC_NO, KC_RALT, KC_RGUI)};


     /* Qwerty
   * ,----------------------------------------------------------------------------------------------------------------------.
   * | ESC  |   1  |   2  |   3  |   4  |   5  |   [  |                    |   ]  |   6  |   7  |   8  |   9  |   0  |Pscree|
   * |------+------+------+------+------+------+------+--------------------+------+------+------+------+------+------+------|
   * |  `   |   Q  |   W  |   E  |   R  |   T  |   -  |                    |   =  |   Y  |   U  |   I  |   O  |   P  |  \   |
   * |------+------+------+------+------+------+------+--------------------+------+------+------+------+------+------+------|
   * | Tab  |   A  |   S  |   D  |   F  |   G  |  Del |                    | Bksp |   H  |   J  |   K  |   L  |   ;  |  "   |
   * |------+------+------+------+------+------+---------------------------+------+------+------+------+------+------+------|
   * | Shift|   Z  |   X  |   C  |   V  |   B  | Space|                    | Enter|   N  |   M  |   ,  |   .  |   /  | Shift|
   * |-------------+------+------+------+------+------+------+------+------+------+------+------+------+------+-------------|
   * | Ctrl |  GUI |  ALt | EISU |||||||| Lower| Space|  Del |||||||| Bksp | Enter| Raise|||||||| Left | Down |  Up  | Right|
   * ,----------------------------------------------------------------------------------------------------------------------.
   */
/*
  [_QWERTY] = LAYOUT( \
    KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_LBRC,                        KC_RBRC, KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_PSCR, \
    KC_GRV,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_MINS,                        KC_EQL , KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_BSLS, \
    KC_TAB,  KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_DEL ,                        KC_BSPC, KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT, \
    KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_SPC ,                        KC_ENT , KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT, \
    KC_LCTL, KC_LGUI, KC_LALT, EISU,             LOWER,   KC_SPC ,KC_DEL,         KC_BSPC,KC_ENT , RAISE,            KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT  \
  ),
*/

