#include QMK_KEYBOARD_H
#include <keymap_jp.h>
#include <sendstring_jis.h>


enum custom_keycodes {
        QMKBEST = SAFE_RANGE,
        Custom1,
        Custom2,
        Custom3,
    };

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case QMKBEST:if (record->event.pressed) SEND_STRING("QMK is the best thing ever!");break;
        case Custom1:if (record->event.pressed) SEND_STRING("ssa");break;
        case Custom2:if (record->event.pressed) SEND_STRING("ssb");break;
        case Custom3:if (record->event.pressed) SEND_STRING("ssc");break;
        // case :if (record->event.pressed) SEND_STRING("");break;
    }
    return true;
};


const key_override_t to0 = ko_make_basic(MOD_MASK_SHIFT, JP_ASTR, JP_TILD );
const key_override_t to1 = ko_make_basic(MOD_MASK_SHIFT, JP_PLUS, JP_DLR );
const key_override_t to2 = ko_make_basic(MOD_MASK_SHIFT, JP_MINS, JP_PERC );
const key_override_t to3 = ko_make_basic(MOD_MASK_SHIFT, JP_DQUO, JP_CIRC );

const key_override_t to4 = ko_make_basic(MOD_MASK_SHIFT, JP_QUOT, JP_GRV );
const key_override_t to5 = ko_make_basic(MOD_MASK_SHIFT, JP_LPRN, JP_RPRN );
const key_override_t to6 = ko_make_basic(MOD_MASK_SHIFT, JP_LCBR, JP_RCBR );
const key_override_t to7 = ko_make_basic(MOD_MASK_SHIFT, JP_LBRC, JP_RBRC );

const key_override_t to8 = ko_make_basic(MOD_MASK_SHIFT, JP_BSLS, JP_YEN );

const key_override_t to9 = ko_make_basic(MOD_MASK_SHIFT, JP_EQL, JP_EXLM );
const key_override_t to10 = ko_make_basic(MOD_MASK_SHIFT, JP_SCLN, JP_AMPR );
const key_override_t to11 = ko_make_basic(MOD_MASK_SHIFT, JP_COLN, JP_QUES );
const key_override_t to12 = ko_make_basic(MOD_MASK_SHIFT, JP_SLSH, JP_PIPE );




// const key_override_t to = ko_make_basic(MOD_MASK_SHIFT, JP_, JP_ );

// This globally defines all key overrides to be used
const key_override_t **key_overrides = (const key_override_t *[]){
    &to0,
    &to1,
    &to2,
    &to3,
    &to4,
    &to5,
    &to6,
    &to7,
    &to8,
    &to9,
    &to10,
    &to11,
    &to12,
    // &to,
    NULL  // Null terminate the array of overrides!
};


// --------------------------------------------------------------------------------------------------------------------------------
// -------------------------map from jsonToC paste this.---------------------------------------------------------------------------
// --------------------------------------------------------------------------------------------------------------------------------

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
        [0] = LAYOUT_4key(KC_GRV, JP_ASTR, JP_PLUS, JP_MINS, JP_DQUO, Custom1, KC_INS, TO(0), Custom2, JP_QUOT, JP_LPRN, JP_LCBR, JP_LBRC, Custom3, KC_ESC, KC_Q, KC_W, KC_E, KC_R, KC_T, JP_AT, JP_BSLS, KC_Y, KC_U, KC_I, KC_O, KC_P, JP_EQL, KC_TAB, KC_A, KC_S, KC_D, KC_F, KC_G, JP_HASH, JP_UNDS, KC_H, KC_J, KC_K, KC_L, JP_SCLN, JP_COLN, TT(1), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_BSPC, KC_GRV, KC_N, KC_M, KC_COMM, KC_DOT, JP_SLSH, KC_DEL, KC_LGUI, KC_LALT, KC_LSFT, KC_LCTL, TT(2), KC_LSFT, KC_SPC, KC_ENT, KC_RSFT, TT(3), KC_RCTL, KC_RSFT, KC_RALT, KC_RGUI),
        [1] = LAYOUT_4key(KC_KANA, KC_CAPS, KC_SLCK, KC_NLCK, KC_PSCR, KC_PAUS, KC_NO, TO(0), KC_PAUS, KC_PSCR, KC_NLCK, KC_SLCK, KC_CAPS, KC_KANA, KC_HENK, KC_F9, KC_F10, KC_F11, KC_F12, KC_MUTE, KC_NO, KC_NO, KC_MUTE, KC_F9, KC_F10, KC_F11, KC_F12, KC_HENK, KC_MHEN, KC_F5, KC_F6, KC_F7, KC_F8, KC_VOLU, KC_APP, KC_APP, KC_VOLU, KC_F5, KC_F6, KC_F7, KC_F8, KC_MHEN, KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_VOLD, KC_NO, KC_NO, KC_VOLD, KC_F1, KC_F2, KC_F3, KC_F4, KC_TRNS, KC_LGUI, KC_LALT, KC_LSFT, KC_LCTL, KC_LALT, KC_LSFT, KC_LCTL, KC_RCTL, KC_RSFT, KC_RALT, KC_RCTL, KC_RSFT, KC_RALT, KC_RGUI),
        [2] = LAYOUT_4key(KC_INS, KC_1, KC_2, KC_3, KC_4, KC_5, KC_NO, TO(0), KC_6, KC_7, KC_8, KC_9, KC_0, KC_NO, KC_DEL, KC_NLCK, KC_P7, KC_P8, KC_P9, KC_PEQL, KC_NO, KC_NO, KC_NO, KC_NO, KC_SPC, KC_TAB, KC_NO, KC_NO, KC_BSPC, KC_P0, KC_P4, KC_P5, KC_P6, KC_PSLS, KC_PCMM, KC_NO, KC_NO, KC_LEFT, KC_UP, KC_DOWN, KC_RGHT, KC_NO, KC_ENT, KC_PDOT, KC_P1, KC_P2, KC_P3, JP_COLN, KC_BSPC, KC_DEL, KC_NO, KC_HOME, KC_PGUP, KC_PGDN, KC_END, KC_NO, KC_LGUI, KC_LALT, KC_LSFT, KC_LCTL, KC_TRNS, KC_LSFT, KC_SPC, KC_ENT, KC_RSFT, KC_NO, KC_RCTL, KC_RSFT, KC_RALT, KC_RGUI),
        [3] = LAYOUT_4key(KC_INS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_DEL, KC_NO, KC_NO, KC_NO, KC_ACL0, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_BTN4, KC_BTN5, KC_NO, KC_NO, KC_BSPC, KC_RALT, KC_LCTL, KC_LSFT, KC_ACL1, KC_NO, KC_NO, KC_NO, KC_NO, KC_MS_L, KC_MS_U, KC_MS_D, KC_MS_R, KC_NO, KC_ENT, KC_NO, KC_NO, KC_NO, KC_ACL2, KC_NO, KC_BTN3, KC_BTN3, KC_NO, KC_WH_L, KC_WH_U, KC_WH_D, KC_WH_R, KC_NO, KC_LGUI, KC_LALT, KC_LSFT, KC_LCTL, KC_NO, KC_BTN1, KC_BTN2, KC_BTN2, KC_BTN1, KC_TRNS, KC_RCTL, KC_RSFT, KC_RALT, KC_RGUI)
};

