#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by csvToKeyMap.
 * You may or may not want to edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
		KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
		KC_NO,KC_UP,KC_UP,KC_UP,KC_UP,KC_NO,KC_NO,KC_LEFT,KC_UP,KC_DOWN,KC_RGHT,KC_NO,
		KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,
		KC_NO,KC_UP,KC_UP,KC_UP,KC_UP,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO
    ),
};

